pub const INPUT_INVALID_OPTION: &str = "PG-IN-001";
pub const CONFIG_LOAD_FAILED: &str = "PG-CFG-001";
pub const GIT_DIFF_FAILED: &str = "PG-GIT-001";
pub const RUNTIME_EVALUATION_FAILED: &str = "PG-RT-001";
pub const OUTPUT_WRITE_FAILED: &str = "PG-OUT-001";
pub const PUBLISH_INPUT_FAILED: &str = "PG-PUB-001";
pub const PUBLISH_API_FAILED: &str = "PG-PUB-002";
pub const PUBLISH_SSO_REQUIRED: &str = "PG-PUB-SSO-001";
pub const PUBLISH_ORG_POLICY_BLOCKED: &str = "PG-PUB-ORG-001";
pub const PUBLISH_WEBHOOK_FAILED: &str = "PG-PUB-WEB-001";
pub const NOTIFICATION_FAILED: &str = "PG-NOT-001";
pub const WAIVER_EXPIRED: &str = "PG-GOV-001";

pub const KNOWN_FAILURE_CODES: &[&str] = &[
    INPUT_INVALID_OPTION,
    CONFIG_LOAD_FAILED,
    GIT_DIFF_FAILED,
    RUNTIME_EVALUATION_FAILED,
    OUTPUT_WRITE_FAILED,
    PUBLISH_INPUT_FAILED,
    PUBLISH_API_FAILED,
    PUBLISH_SSO_REQUIRED,
    PUBLISH_ORG_POLICY_BLOCKED,
    PUBLISH_WEBHOOK_FAILED,
    NOTIFICATION_FAILED,
    WAIVER_EXPIRED,
];
